---
deployment:
  tasks:
    - source /home/qqjjkxng/virtualenv/test.lumina.com.ng/backend/3.10/bin/activate
    - pip install -r requirements.txt
    - python manage.py migrate
    - python manage.py collectstatic --noinput
