# Generated by Django 5.1.1 on 2024-01-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='static/uploads'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='matric_number',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
