# Generated by Django 5.1.1 on 2024-01-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='department',
            field=models.CharField(default='Information Technology', max_length=255),
            preserve_default=False,
        ),
    ]
