# Generated by Django 5.1.1 on 2024-01-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_studentprofile_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='faculty',
            field=models.CharField(default='School of Computing', max_length=255),
            preserve_default=False,
        ),
    ]
