# Generated by Django 5.1.1 on 2024-01-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_studentprofile_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='static/uploads'),
        ),
    ]
